### ISSUE TITLE
Function names

### ISSUE THREAD

**Issue by erikhw** [insongkim/wfe#1]
I suggest that we have a function `PanelMatch` that does the matching, all the way down to a list of matched sets (with the corresponding treated units). 

I anticipate that the function users would most often employ would be something that directly gives them estimation results along with confidence intervals. I wonder if `PanelEstimate` would be a good name. I suppose that we will have `PanelMatch` in our namespace, but will also embed it in `PanelEstimate` as well. When using `PanelEstimate`, users can choose to "skip" `PanelMatch` if they already call `PanelMatch` separately beforehand. That way `PanelEstimate` will simply use the list of matched sets that the users separately created. Importantly, if they do not execute `PanelMatch` beforehand, then `PanelEstimate` will do it for them. In `PanelEstimate`, they will choose `L`, `FORWARD` for the number of lags and forwards along with one of the estimation schemes, `Maha`, `Pscore` and `Synth`. They will also choose an inferential procedure between regression standard errors and weighted bootstrap. 

Note that the list of objects `PanelEstimate` produces and stores should not include things relevant to estimates and confidence intervals, but also the `PanelMatch` object. In other words, if users do not execute `PanelMatch` beforehand and let `PanelEstimate` do it for them, then we will store the list of matched sets as an output in the `PanelEstimate` function. This way users can easily apply `PanelDiagnostics` to this list of matched sets, which will be our separate function for diagnostics.

In addition, we will let the original `wfe` function have an option to select `L` as well. Users will execute `PanelMatch` beforehand, and then `wfe` will use the list of matched sets to produce results identical to `PanelEstimate` with regression standard errors when `L` is selected.

@kosukeimai @insongkim

**Comment by kosukeimai** [comment]
Yes, that sounds good.  `PanelDiagnostics` might be too long as a function name.  What about `PanelDiagnose`?  Also, `L` is not very intuitive.  I suggest `lag`.  Instead of `FORWARD`, you may use `lead`, which is opposite of `lag`.

**Comment by erikhw** [comment]
> PanelDiagnostics might be too long as a function name. What about PanelDiagnose? Also, L is not very intuitive. I suggest lag. Instead of FORWARD, you may use lead, which is opposite of lag.

Will do.
