### ISSUE TITLE
Panel data inquiry

### ISSUE THREAD

**Issue by francobeltran** [insongkim/wfe#4]
Hi. I have been trying to run your package on a cross sectional data set. So far the only way I get wfe to work is if I collapse/summarize the dataset by "unit" and "time." In my dataset unit stands state and time for year. Whenever I run wfe on individual observations, i.e. without collapsing, I get  the following error:

Error in `$<-.data.frame`(`*tmp*`, "W.it", value = numeric(0)) : 
  replacement has 0 rows, data has 4231

This becomes a limitation as within the same unit and time cell, according to my identification, some units may  be treated and others not. If I collapse data by unit and time, treatment stops being a binary (0/1) and since wfe requires this, the code breaks. Turning this continuous variable into a binary by rounding up solves the issue but estimates have a completely different interpretation.  Is there any option within the wfe package that accounts for this?

Best,
Franco

**Comment by insongkim** [comment]
Thanks for using the package. Unfortunately, the methods works only for a panel dataset with a binary treatment, and it currently does not accommodate continuous treatment. As you described, you could set `method = “unit”` or `method = “time”` to adjust for state- *or* time-specific one-way fixed effects.

**Comment by francobeltran** [comment]
I understand. Thank you very much for your quick response.
